In [1]:
import numpy as np;

In [ ]:
#Multiplication of Matrix Using Numpy 

In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[3,2,1],[6,5,4],[9,8,7]])

In [118]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
b

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
a.dot(b)

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [21]:
#Create a programme to change a string element in a specified Numpy array to Uppercase ,Lowercase ,capital the first letter , title case or swapcase

In [22]:
my_arr = np.array(["I","Love","bangalore"])

In [23]:
type(my_arr)

numpy.ndarray

In [24]:
my_arr.shape

(3,)

In [27]:
up=np.char.upper(my_arr)
up

array(['I', 'LOVE', 'BANGALORE'], dtype='<U9')

In [28]:
lc = np.char.lower(my_arr)
lc

array(['i', 'love', 'bangalore'], dtype='<U9')

In [30]:
cap = np.char.capitalize(my_arr)
cap

array(['I', 'Love', 'Bangalore'], dtype='<U9')

In [31]:
tit = np.char.title(my_arr)
tit

array(['I', 'Love', 'Bangalore'], dtype='<U9')

In [32]:
res = np.char.swapcase(my_arr)
res

array(['i', 'lOVE', 'BANGALORE'], dtype='<U9')

In [33]:
#Get row number of numpyarray if any element is having larger than a specifieed values(x=10)

In [ ]:
x=10

In [34]:
a = np.array([[1,2,3,4,5],[10,-3,40,32,9],[3,6,2,8,5],[11,2,1,4,3],[9,8,7,6,5]])
a

array([[ 1,  2,  3,  4,  5],
       [10, -3, 40, 32,  9],
       [ 3,  6,  2,  8,  5],
       [11,  2,  1,  4,  3],
       [ 9,  8,  7,  6,  5]])

In [37]:
x = 10

In [39]:
np.where(np.any(a > x , axis =1))

(array([1, 3]),)

In [40]:
# Remove rows with Null values in Numpy Array

In [52]:
z = np.array([
    [23, 44, 11,76,98],
    [78, 34, np.nan,89,90],
    [34, 12, 23,np.nan,65]
])
z

array([[23., 44., 11., 76., 98.],
       [78., 34., nan, 89., 90.],
       [34., 12., 23., nan, 65.]])

In [54]:
z.shape

(3, 5)

In [55]:
np.isnan(z)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [58]:
z[~np.isnan(z).any(axis=1)]

array([[23., 44., 11., 76., 98.]])

In [59]:
#Multiply String Elements in Numpy Array

In [60]:
3*"Apple"

'AppleAppleApple'

In [62]:
s = np.array(['nish','nik','shah','naya'])
s

array(['nish', 'nik', 'shah', 'naya'], dtype='<U4')

In [64]:
np.char.multiply(s,3)`

array(['nishnishnish', 'nikniknik', 'shahshahshah', 'nayanayanaya'],
      dtype='<U12')

In [65]:
#Find the minimum value with Numpy along axis

In [70]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.max(a,axis=1)

array([3, 6, 9])

In [74]:
np.min(a,axis=1)

array([1, 4, 7])

In [75]:
# Fill diagonal value in Numpy Array 

In [76]:
k = np.array([[9,8],[2,3]])
k

array([[9, 8],
       [2, 3]])

In [77]:
x = 5

In [83]:
np.fill_diagonal(k, x)


In [84]:
print(k)

[[5 8]
 [2 5]]


In [85]:
# Checking and filling number in Numpy Array

In [87]:
v=np.array([[23,45,67],[12,45,89]])
v

array([[23, 45, 67],
       [12, 45, 89]])

In [89]:
np.isin(v,67)

array([[False, False,  True],
       [False, False, False]])

In [90]:
v[v < 23] = 8
v

array([[23, 45, 67],
       [ 8, 45, 89]])

In [91]:
# Reshaping and create new Numpy Array and reverse it

In [93]:
z = np.arange(16).reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
q =z[::-1]
q

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [95]:
# Padding in Numpy Array

In [96]:
j = np.ones((2,2))
j

array([[1., 1.],
       [1., 1.]])

In [99]:
np.pad(j,pad_width=1,mode = 'constant',constant_values =  0)

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [100]:
# Sine and Cosine

In [101]:
degrees = np.array([0,30, 45,60, 90])
np.sin(degrees)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [102]:
new_degrees = degrees * np.pi/180
np.sin(new_degrees)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [103]:
# Compare two Numpy Arrays

In [104]:
a = np.array([121,23,45])
b=np.array([234,12,42])
a > b

array([False,  True,  True])

In [105]:
# How to Stack two Arrays in NumPy

In [111]:
a = np.arange(10).reshape(5,2)
b = np.arange(10,20).reshape(5,2)


array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [112]:
np.concatenate([a,b],axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [113]:
np.vstack([a,b])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [114]:
np.hstack([a,b])

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [116]:
b.itemsize

8